services:
  stl-generator:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./temp:/app/temp
      - ./src/templates:/app/src/templates:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped